export const ERROR = {
  SWEAR_WORD: 'SWEAR_WORD', // 비속어 발견
  DUPLICATION: 'DUPLICATION', // 중복 작성
  AUTHENTICATION: 'AUTHENTICATION', // 인증에러
  EID_AUTHENTICATION: 'EID_AUTHENTICATION', // 인증에러
  EID_REFRESH_AUTHENTICATION: 'EID_REFRESH_AUTHENTICATION', // 인증에러
  AUTHORIZATION: 'AUTHORIZATION', // 권한에러
  NOT_EXIST_DATA: 'NOT_EXIST_DATA', // 해당 데이터 없음
  UNKNOWN_APP_ID: 'UNKNOWN_APP_ID', // 비정상적인 앱 접근
};
