name: Build and Push Docker Image

on:
  push:
    branches: [master] # Change to your target branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables for Debug
        run: echo "${{ secrets.ENV_DEBUG }}" > .env.debug

      - name: Set environment variables for Staging
        run: echo "${{ secrets.ENV_STAGING }}" > .env.staging

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Private Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/seoulsync-backend:latest

      - name: Send HTTP API POST Request
        run: |
          curl -X 'POST' \
            'http://${{ secrets.HOST_NAME }}/container/update/seoulsync' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: ${{ secrets.API_TOKEN }}' \
            -d '{
                  "type": "backend",
                  "host_port": 7008,
                  "container_port": 3456
              }'
        env:
          HOST_NAME: ${{ secrets.NAS_MANAGE_HOST }}
          API_TOKEN: ${{ secrets.NAS_MANAGE_PASSWORD }}
